# 阿里云千问API配置
aliyun:
  api_key: "your_api_key_here"  # 请替换为您的阿里云API密钥
  api_url: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
  model: "qwen-turbo"

# Qdrant向量数据库配置
qdrant:
  endpoint: "http://localhost:6333"
  collection: "resumes"
  dimension: 1024

# 注意: 复制此文件为 config.yaml 并填入您的实际 API 密钥 